title: The Narmaya Bible
description: A comprehensive guide for playing Narmaya in Granblue Fantasy Versus Rising
theme: just-the-docs

favicon_ico: "/assets/favicon.png"

url: https://tsubasamanda.github.io/narmaya-bible/

aux_links:
  GBVSR Dustloop: https://www.dustloop.com/w/GBVSR

aux_links_new_tab: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/tsubasamanda/narmaya-bible" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately